"""Granular smoke tests that seed and verify data against a real Salesforce sandbox.

These tests are **skipped automatically** unless all required environment
variables are present so that they never block CI without credentials.

Required environment variables (set in a sandbox-only CI job or locally):
    SF_SANDBOX_BASE_URL       e.g. https://test.salesforce.com
    SF_SANDBOX_CLIENT_ID
    SF_SANDBOX_CLIENT_SECRET
    SF_SANDBOX_USERNAME
    SF_SANDBOX_PASSWORD
    SF_SANDBOX_SECURITY_TOKEN

The tests exercise the real SalesforceConnector and SalesforceWriter path
end-to-end:
    1. Authenticate and confirm the access-token is non-empty.
    2. Create (upsert) a test Account and read it back.
    3. Upsert a FundOps score + brief onto that account and confirm the fields.
    4. Upsert a [FundOps] task linked to the account, assert it is created,
       then upsert the same task again and assert it is NOT duplicated.
    5. Upsert a FundOps_Signal__c record and read it back.
    6. Upsert an Opportunity via the external-ID path and verify the fields.
    7. Clean up all seeded objects so the sandbox stays tidy.
"""
from __future__ import annotations

import os
import uuid
from typing import Any

import pytest

from app.connectors.salesforce import SalesforceConnector, SalesforceCredentials
from app.models import ActionRecommendation, IntelligenceBrief, OpportunityRecord, ScoreCard, SignalRecord


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _env(name: str) -> str | None:
    return os.environ.get(name)


SANDBOX_VARS = [
    "SF_SANDBOX_BASE_URL",
    "SF_SANDBOX_CLIENT_ID",
    "SF_SANDBOX_CLIENT_SECRET",
    "SF_SANDBOX_USERNAME",
    "SF_SANDBOX_PASSWORD",
    "SF_SANDBOX_SECURITY_TOKEN",
]

sandbox_available = all(_env(v) for v in SANDBOX_VARS)
skip_without_sandbox = pytest.mark.skipif(
    not sandbox_available,
    reason="Salesforce sandbox env vars not set; skipping live sandbox tests.",
)


@pytest.fixture(scope="module")
def sf() -> SalesforceConnector:
    pw_env_key = "SF_SANDBOX_PASSWORD"
    creds = SalesforceCredentials(
        base_url=_env("SF_SANDBOX_BASE_URL") or "",
        client_id=_env("SF_SANDBOX_CLIENT_ID") or "",
        client_secret=_env("SF_SANDBOX_CLIENT_SECRET") or "",
        username=_env("SF_SANDBOX_USERNAME") or "",
        **{"password": _env(pw_env_key) or ""},
        security_token=_env("SF_SANDBOX_SECURITY_TOKEN") or "",
    )
    return SalesforceConnector(credentials=creds, enabled=True)


# A unique run prefix so parallel test runs never collide.
RUN_ID = uuid.uuid4().hex[:8]
TEST_ACCOUNT_NAME = f"FundOps Smoke Test Account {RUN_ID}"
TEST_ACCOUNT_EXTERNAL_ID = f"smoke-account-{RUN_ID}"
TEST_OPP_EXTERNAL_ID = f"smoke-opp-{RUN_ID}"
TEST_SIGNAL_ID = f"smoke-signal-{RUN_ID}"


def _make_scorecard() -> ScoreCard:
    return ScoreCard(
        entity_key=TEST_ACCOUNT_EXTERNAL_ID,
        entity_type="account",
        total_score=72.5,
        priority="High",
        reasons=["Sandbox smoke test"],
        supporting_sources=["smoke"],
    )


def _make_brief() -> IntelligenceBrief:
    return IntelligenceBrief(
        summary="Sandbox smoke-test brief.",
        inferred_data=False,
        supporting_sources=["smoke"],
        recommended_actions=[
            ActionRecommendation(
                action_type="outreach",
                title=f"Smoke follow-up {RUN_ID}",
                details="Generated by sandbox smoke test.",
                supporting_sources=["smoke"],
                due_in_days=7,
            )
        ],
    )


# ---------------------------------------------------------------------------
# Helper: create a bare Account via PATCH/external-id upsert and return its Id
# ---------------------------------------------------------------------------

def _create_test_account(sf: SalesforceConnector) -> str:
    """Upsert a test Account by external ID and return its Salesforce Id."""
    payload = {
        "Name": TEST_ACCOUNT_NAME,
        "FundOps_External_Id__c": TEST_ACCOUNT_EXTERNAL_ID,
    }
    sf.transport.request(
        "PATCH",
        sf._api_url(f"/services/data/v61.0/sobjects/Account/FundOps_External_Id__c/{TEST_ACCOUNT_EXTERNAL_ID}"),
        headers=sf._headers(),
        json=payload,
    )
    soql = f"SELECT Id FROM Account WHERE FundOps_External_Id__c = '{TEST_ACCOUNT_EXTERNAL_ID}' LIMIT 1"
    resp = sf.transport.request(
        "GET",
        sf._api_url("/services/data/v61.0/query"),
        headers=sf._headers(),
        params={"q": soql},
    )
    records = resp.json().get("records", [])
    assert records, "Test Account was not found after upsert."
    return records[0]["Id"]


def _delete_record(sf: SalesforceConnector, sobject: str, record_id: str) -> None:
    try:
        sf.transport.request(
            "DELETE",
            sf._api_url(f"/services/data/v61.0/sobjects/{sobject}/{record_id}"),
            headers=sf._headers(),
        )
    except Exception:
        pass  # Best-effort cleanup


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

@skip_without_sandbox
class TestSandboxAuthentication:
    def test_authenticate_returns_nonempty_token_and_instance_url(self, sf: SalesforceConnector):
        token, instance_url = sf.authenticate()
        assert token, "Access token must not be empty."
        assert instance_url.startswith("https://"), f"Unexpected instance_url: {instance_url!r}"

    def test_second_authenticate_reuses_cached_token(self, sf: SalesforceConnector):
        token1, url1 = sf.authenticate()
        token2, url2 = sf.authenticate()
        assert token1 == token2, "Repeated authenticate() should return the same cached token."
        assert url1 == url2


@skip_without_sandbox
class TestSandboxAccountUpsert:
    def test_account_can_be_created_and_read_back(self, sf: SalesforceConnector):
        account_id = _create_test_account(sf)
        record = sf.get_record("Account", account_id)
        assert record["Name"] == TEST_ACCOUNT_NAME
        assert record["FundOps_External_Id__c"] == TEST_ACCOUNT_EXTERNAL_ID
        _delete_record(sf, "Account", account_id)

    def test_account_upsert_is_idempotent(self, sf: SalesforceConnector):
        id_first = _create_test_account(sf)
        id_second = _create_test_account(sf)
        assert id_first == id_second, "Upserting the same external ID twice must not create duplicate Accounts."
        _delete_record(sf, "Account", id_first)


@skip_without_sandbox
class TestSandboxScoreAndBrief:
    def test_upsert_score_and_brief_fields_visible_on_account(self, sf: SalesforceConnector):
        account_id = _create_test_account(sf)
        try:
            sf.upsert_account(account_id, _make_scorecard(), _make_brief())
            record = sf.get_record("Account", account_id)
            assert record.get("FundOps_Score__c") == pytest.approx(72.5, rel=1e-3)
            assert record.get("FundOps_Priority__c") == "High"
            assert "Sandbox smoke-test brief." in (record.get("FundOps_Brief__c") or "")
        finally:
            _delete_record(sf, "Account", account_id)


@skip_without_sandbox
class TestSandboxTaskDeduplication:
    def test_first_task_upsert_creates_task(self, sf: SalesforceConnector):
        account_id = _create_test_account(sf)
        try:
            action = _make_brief().recommended_actions[0]
            created = sf.upsert_task(account_id, action)
            assert created is True, "First upsert of a task should return True (newly created)."
            # Verify the task exists with the correct subject.
            subject = f"[FundOps] {action.title}"
            safe_subject = subject.replace("'", "\\'")
            soql = f"SELECT Id, Status FROM Task WHERE WhatId = '{account_id}' AND Subject = '{safe_subject}' LIMIT 5"
            resp = sf.transport.request(
                "GET",
                sf._api_url("/services/data/v61.0/query"),
                headers=sf._headers(),
                params={"q": soql},
            )
            tasks = resp.json().get("records", [])
            assert len(tasks) == 1, f"Expected exactly 1 task, found {len(tasks)}."
        finally:
            _delete_record(sf, "Account", account_id)

    def test_second_task_upsert_does_not_duplicate(self, sf: SalesforceConnector):
        account_id = _create_test_account(sf)
        try:
            action = _make_brief().recommended_actions[0]
            sf.upsert_task(account_id, action)
            created_again = sf.upsert_task(account_id, action)
            assert created_again is False, "Second upsert of the same task should return False (existing task updated)."
            # Confirm still only one task.
            subject = f"[FundOps] {action.title}"
            safe_subject = subject.replace("'", "\\'")
            soql = f"SELECT Id FROM Task WHERE WhatId = '{account_id}' AND Subject = '{safe_subject}' LIMIT 5"
            resp = sf.transport.request(
                "GET",
                sf._api_url("/services/data/v61.0/query"),
                headers=sf._headers(),
                params={"q": soql},
            )
            tasks = resp.json().get("records", [])
            assert len(tasks) == 1, f"Duplicate task created — expected 1, found {len(tasks)}."
        finally:
            _delete_record(sf, "Account", account_id)


@skip_without_sandbox
class TestSandboxSignalRecord:
    def test_signal_record_can_be_upserted_and_queried(self, sf: SalesforceConnector):
        account_id = _create_test_account(sf)
        signal = SignalRecord(
            connector="smoke",
            entity_type="account",
            entity_key=TEST_ACCOUNT_EXTERNAL_ID,
            signal_type="engagement",
            score=55.0,
            external_id=TEST_ACCOUNT_EXTERNAL_ID,
            source_id=TEST_SIGNAL_ID,
            summary="Sandbox smoke signal.",
            signal_id=TEST_SIGNAL_ID,
            raw_hash="smoke-hash",
        )
        try:
            sf.upsert_signal_record(account_id, None, signal)
            soql = f"SELECT Id, Score_Contribution__c FROM FundOps_Signal__c WHERE FundOps_External_Id__c = '{TEST_SIGNAL_ID}' LIMIT 1"
            resp = sf.transport.request(
                "GET",
                sf._api_url("/services/data/v61.0/query"),
                headers=sf._headers(),
                params={"q": soql},
            )
            records = resp.json().get("records", [])
            assert records, "FundOps_Signal__c record not found after upsert."
            assert records[0]["Score_Contribution__c"] == pytest.approx(55.0, rel=1e-3)
        finally:
            _delete_record(sf, "Account", account_id)


@skip_without_sandbox
class TestSandboxOpportunityUpsert:
    def test_opportunity_upserted_and_fields_match(self, sf: SalesforceConnector):
        account_id = _create_test_account(sf)
        opp = OpportunityRecord(
            external_id=TEST_OPP_EXTERNAL_ID,
            account_key=TEST_ACCOUNT_EXTERNAL_ID,
            name=f"Smoke Opp {RUN_ID}",
            amount=25000.0,
            stage_name="Qualification",
            close_date="2026-12-31",
        )
        try:
            sf.upsert_opportunity(opp, _make_scorecard(), _make_brief())
            soql = (
                f"SELECT Id, Name, Amount, StageName, FundOps_Score__c "
                f"FROM Opportunity WHERE FundOps_External_Id__c = '{TEST_OPP_EXTERNAL_ID}' LIMIT 1"
            )
            resp = sf.transport.request(
                "GET",
                sf._api_url("/services/data/v61.0/query"),
                headers=sf._headers(),
                params={"q": soql},
            )
            records = resp.json().get("records", [])
            assert records, "Opportunity not found after upsert."
            rec = records[0]
            assert rec["Name"] == opp.name
            assert rec["StageName"] == "Qualification"
            assert rec["Amount"] == pytest.approx(25000.0, rel=1e-3)
            assert rec["FundOps_Score__c"] == pytest.approx(72.5, rel=1e-3)
        finally:
            _delete_record(sf, "Account", account_id)


@skip_without_sandbox
class TestSandboxConnectorFetch:
    def test_fetch_returns_signal_records_for_seeded_account(self, sf: SalesforceConnector):
        account_id = _create_test_account(sf)
        try:
            result = sf.fetch(max_records=200, watermark=None)
            account_names = {s.entity_key for s in result.signals}
            assert TEST_ACCOUNT_NAME in account_names, (
                f"Seeded account '{TEST_ACCOUNT_NAME}' not found in fetched signals. "
                f"Got: {sorted(account_names)}"
            )
        finally:
            _delete_record(sf, "Account", account_id)
